name: Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox]

    steps:
      - name: Repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Instalar navegadores Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar tests Playwright
        run: npx playwright test --project=${{ matrix.browser }}

      - name: Generar reporte Allure
        if: always()
        run: |
          npm run allure:generate

      - name: Subir reporte Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.browser }}
          path: allure-report
